/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package usolibreriamorse;
import morsafinal.LibreriaMorse;
/**
 *
 * @author enriq
 */
public class PruebaVisual extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PruebaVisual.class.getName());
    LibreriaMorse Morse;
    /**
     * Creates new form PruebaVisual
     */
    public PruebaVisual() {
        initComponents();
        Morse=new LibreriaMorse();        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxOpciones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblEleccion = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        txtFrase = new javax.swing.JTextField();
        btnTraducir = new javax.swing.JButton();
        btnEscuchar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbxOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal-Morse", "Morse-Normal", "Morse-audioMorse", "Normal-audioMorse", "Normal-binario", "binario-normal" }));
        cbxOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxOpcionesMouseClicked(evt);
            }
        });
        cbxOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOpcionesActionPerformed(evt);
            }
        });

        jLabel2.setText("SELECCIONA UNA OPCION");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEleccion.setBackground(new java.awt.Color(255, 255, 255));
        lblEleccion.setText("Opcion Elegida:");
        lblEleccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFraseActionPerformed(evt);
            }
        });

        btnTraducir.setText("Traducir");
        btnTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraducirActionPerformed(evt);
            }
        });

        btnEscuchar.setText("Esuchar");
        btnEscuchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscucharActionPerformed(evt);
            }
        });

        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTraducir)
                        .addGap(38, 38, 38)
                        .addComponent(btnEscuchar))
                    .addComponent(lblResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEleccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFrase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFrase))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(lblEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTraducir)
                    .addComponent(btnEscuchar))
                .addGap(18, 18, 18)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFraseActionPerformed

    private void cbxOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxOpcionesMouseClicked
        
    }//GEN-LAST:event_cbxOpcionesMouseClicked

    private void cbxOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOpcionesActionPerformed
        // TODO add your handling code here:
        if(cbxOpciones.getSelectedItem().equals("Normal-Morse")){lblEleccion.setText("Opcion Elegida: Traducción Normal A Morse");
            btnEscuchar.setEnabled(false);
            btnTraducir.setEnabled(true);
            lblResultado.setVisible(true);
            txtFrase.setText("");
            lblResultado.setText("");
            lblFrase.setText("Ingresa el texto");}
        else if (cbxOpciones.getSelectedItem().equals("Morse-Normal")){
            btnEscuchar.setEnabled(false);
            btnTraducir.setEnabled(true);
            lblResultado.setVisible(true);
            txtFrase.setText("");
            lblResultado.setText("");
            lblEleccion.setText("Opcion Elegida: Traducción Morse A Normal");
            lblFrase.setText("Ingresa el codigo Morse");
        }
        else if (cbxOpciones.getSelectedItem().equals("Morse-audioMorse")){
            txtFrase.setText("");
            lblResultado.setText("");
            lblEleccion.setText("Opcion Elegida: Esuchar el codigo Morse");
            lblFrase.setText("Ingresa el codigo Morse");
            btnEscuchar.setEnabled(true);  
            btnTraducir.setEnabled(false);
            lblResultado.setVisible(false);
            
        
        } 
        else if (cbxOpciones.getSelectedItem().equals("Normal-audioMorse")){
            lblResultado.setVisible(false);
            txtFrase.setText("");
            lblResultado.setText("");
            btnEscuchar.setEnabled(true);    
            lblEleccion.setText("Opcion Elegida: Traducción Normal A su audio en Morse");
            lblFrase.setText("Ingresa el texto a traducir");
            btnTraducir.setEnabled(false);
        
        } 
        else if (cbxOpciones.getSelectedItem().equals("Normal-binario")){
            btnTraducir.setEnabled(true);
            btnEscuchar.setEnabled(false); 
            lblResultado.setVisible(true);
            txtFrase.setText("");
            lblResultado.setText("");
            lblEleccion.setText("Opcion Elegida: Traducción Normal A Binario");
            lblFrase.setText("Ingresa el texto normal");
        }
        else if (cbxOpciones.getSelectedItem().equals("binario-normal")){
            btnTraducir.setEnabled(true);
            btnEscuchar.setEnabled(false);
            lblResultado.setVisible(true);
            txtFrase.setText("");
            lblResultado.setText("");
            lblEleccion.setText("Opcion Elegida: Traducción binario A Normal");
            lblFrase.setText("Ingresa el codigo binario");
        }
    }//GEN-LAST:event_cbxOpcionesActionPerformed

    private void btnTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraducirActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(cbxOpciones.getSelectedItem().equals("Normal-Morse")){  
            lblResultado.setText(Morse.normalAMorse(txtFrase.getText())); 
        }
        else if (cbxOpciones.getSelectedItem().equals("Morse-Normal")){
            lblResultado.setText(Morse.morseANormal(txtFrase.getText()));    
        }
        else if (cbxOpciones.getSelectedItem().equals("Morse-audioMorse")){
                    
        } 
        else if (cbxOpciones.getSelectedItem().equals("Normal-audioMorse")){
            
        
        } 
        else if (cbxOpciones.getSelectedItem().equals("Normal-binario")){
            lblResultado.setText(Morse.palabraABinario(txtFrase.getText()));
        
        }
        else if (cbxOpciones.getSelectedItem().equals("binario-normal")){
            lblResultado.setText(Morse.binarioAAscii(txtFrase.getText()));

        }
    }//GEN-LAST:event_btnTraducirActionPerformed

    private void btnEscucharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscucharActionPerformed
        // TODO add your handling code here:
        if (cbxOpciones.getSelectedItem().equals("Normal-audioMorse")){
            Morse.normalAsonido(txtFrase.getText());}
        else if(cbxOpciones.getSelectedItem().equals("Morse-audioMorse")){
            Morse.morseASonido(txtFrase.getText());
        }
    }//GEN-LAST:event_btnEscucharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PruebaVisual().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscuchar;
    private javax.swing.JButton btnTraducir;
    private javax.swing.JComboBox<String> cbxOpciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEleccion;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtFrase;
    // End of variables declaration//GEN-END:variables
}
